name: Path Filter Test

on:
  push:
    paths:
    - 'data/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo
        run: echo "Hello, world!"
